### ISSUE TITLE
Client - Update/Add Milestones, Message and Receipt Node Events API

### ISSUE THREAD

**Issue by rebinmannady93** [iotaledger/iota.c#404]
[EVENT API DOC](https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/iotaledger/tips/stardust-event-api/tips/TIP-0028/event-api.yml)
- [ ] milestone-info/latest - change topic string and update response
- [ ] milestone-info/confirmed - change topic and update response
- [ ] milestones - add new topic
- [ ] messages/transaction/tagged-data - add new topic
- [ ] message-metadata/referenced - change topic string
- [ ] message-metadata/{messageId} - change topic string
~~- [ ] receipts - add new topic~~
